### ISSUE TITLE
Readme is duplicated

### ISSUE THREAD

**Issue by calaway** [applegrain/creact#27]
The markdown in the readme is duplicated. Once you get to the end of the tutorial, you're only halfway through the markdown and then it starts over. I would delete the second half and submit a PR, but I don't know if the two halves are exactly the same, so I don't want to accidentally delete something that shouldn't be deleted.   😕

**Comment by biglovisa** [comment]
Ah shit. Thought I had fixed that. I'll push up a change soon! Thanks @calaway
