### ISSUE TITLE
Inconsistent line

### ISSUE THREAD

**Issue by MowAlon** [applegrain/creact#7]
At the end of section 7, the review of the code for the _all_skills.js.jsx file has this line:
    let skills = this.props.skills.map((skill) => {

.... but all the code listed prior to that says 'var skills......'

**Comment by biglovisa** [comment]
Thanks, I'll fix this now.

**Comment by biglovisa** [comment]
Fixed with https://github.com/applegrain/creact/commit/743245695d57df1bd26952f69974782fd4f67ef5
